- name: Commit and push changes
  env:
    GH_TOKEN: ${{ secrets.GH_PAT }}
  run: |
    git config --global user.name 'github-actions[bot]'
    git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    git stash  # 변경사항 임시 저장
    git pull origin main --rebase
    git stash pop || true  # stash 꺼내기. 충돌나도 무시
    git add .
    git commit -m "Update blog post" || echo "Nothing to commit"
    git push https://$GH_TOKEN@github.com/shj78/velog.git
